### ISSUE TITLE
Update the bindings to Linux 5.13

### ISSUE THREAD

**Issue by sboeuf** [rust-vmm/kvm-bindings#41] opened 2021-07-07 09:41 UTC
I was wondering what's the correct process to update the bindings to 5.13. There are some new KVM ioctls and capabilities which I would like to leverage, but they've been added after 4.20.
/cc @andreeaflorescu

**Comment by andreeaflorescu** [comment] 2021-07-07 09:53
This is an interesting discussion. So technically the bindings should be backwards compatible, so we could for example drop the 4.20 and 4.14 bindings, and switch to the newer ones.

I guess though that this will require changes in the versionized bindings as well? Can we do a dry run to see what is needed?

**Comment by sboeuf** [comment] 2021-07-07 10:02
Yes exactly, Linux always maintain backward compatibility so we should be fine.
The question is, how were generated these bindings in the first place? And did we add some extra things on top of the automatically generated code?
If you have the instructions on how to do that, I can certainly run them on 5.13 and submit a PR which we can test and validate before we decide to fully remove 4.14 and 4.20.

**Comment by andreeaflorescu** [comment] 2021-07-07 10:29
> The question is, how were generated these bindings in the first place?

The process is documented here: https://github.com/rust-vmm/kvm-bindings/blob/master/CONTRIBUTING.md

> And did we add some extra things on top of the automatically generated code?

Yes, we did (at least this is how I remember it). But I think that the problems we encountered might have been fixed in newer versions. One thing that has been quite painful is that we do not derive all that can be derived when we generated the bindings (things such as PartialEq, Debug are super useful, so we need to make sure to include them). These were manually added for a few strucutres.

I remember that there was also a problem with the padding of a structure that we need to manually fix (the tests were failing so it was straightforward to identify the problem). The problem is that the history of those changes is somewhere in Firecracker as I initially just took all the code from there and dumped it in the now deprecated kvm-wrapper, which later became kvm-bindings. Instead of going through the history now, I think we can just regenerate it and check what's change between the generated bindings for 5.13 and the current bindings.

**Comment by andreeaflorescu** [comment] 2021-07-07 10:30
BTW, if the steps from the contributing document no longer work, could you update them as you regenerate the bindings?

**Comment by sboeuf** [comment] 2021-07-07 15:33
Generating the bindings is quite easy following the instructions you pointed out. One thing to note is that I could only do `arm64` and `x86_64` since `arm` headers didn't contain `kvm.h` for some reason :-/
Does it make sense to keep `arm` when we have `arm64`?

Anyway, the very painful thing is to derive Serialize and Deserialize from `serde`, which is not handled by `bindgen`. The problem is that I'm trying to validate the generated bindings work correctly with Cloud-Hypervisor, but that means I need to derive all the structures we derived in the 4_20_0 version.
Do you have any tool for doing such thing based on the structures/enums names? I've been trying to regex all structs and enums by extending their derive, but I ran into some issues. So I think the proper solution is to maintain a list of structures which should be serialized for every time we try to update the bindings. Of course this is Cloud-Hypervisor specific for now, but I don't know how to properly test the generated bindings otherwise.

**Comment by sboeuf** [comment] 2021-07-07 19:34
Ok I manually edited the `bindings_5_13_0.rs` file to apply only the serde serialization we need, and I can confirm it works well.
I'm gonna send a PR to this repo with the bindings directly generated out of `bindgen`.

**Closed** 2022-08-20 16:12 UTC
